#!/bin/bash
############################################
# dimensions [MATRIX] - accepts one matrix
# and prints the # of rows and # columns.
############################################
dimensions() {
row=0
col=0
while read myLine
do
	col=0
	row=`expr $row + 1`
	for i in $myLine
	do
		col=`expr $col + 1`
	done
done<$matrix1
echo "$row $col"
exit 0
}

############################################
# transpose [MATRIX] - accepts one matrix
# and prints the transpose of that matrix.
############################################
transpose() {
echo "transpose"
}

############################################
# mean [MATRIX] - accepts one matrix and 
# prints the mean of each columns numbers.
############################################
mean() {
echo "mean"
}

############################################
# add [MATRIX_1] [MATRIX_2] - accepts 
# exactly 2 matrices and if they're valid,
# they print out the summed matrix.
############################################
add() {
echo "add"
}

############################################
# multiply [MATRIX_1] [MATRIX_2] - accepts
# exaclty 2 matrices and if they're valid, 
# they print out the product matrix.
############################################
multiply() {
echo "multiply"
}

# Read first argument to determine what function to run
func=$1
numArg=$#
echo "First arguement: $func"

################################
# Check for dims function
if [ $func == "dims" ]
then 
	echo "Number of arguments entered: $numArg"
	echo "Entered function: dims"
	# Confirm only one argument is entered
	if [ $# == 2 ]
	then
		echo "valid # of arguments"
		matrix1=$2
		# confirm matrix argument is readable
		if [ -r $matrix1 ]
		then
			dimensions matrix1
			exit 0
		else
			echo "Unable to read file $matrix1" 1>&2
			exit 1
		fi
	else
		echo "Invalid # of arguments" 1>&2
		exit 1
	fi

###############################
# Check for mean function
elif [ $func == "mean" ]
then
	echo "Entered function: mean"

###############################
# Check for transpose function
elif [ $func == "transpose" ]
then
	echo "Entered function: transpose"

###############################
# Check for add function
elif [ $func == "add" ]
then
	echo "Entered function: add"

###############################
# Check for multiply function
elif [ $func == "mutiply" ]
then
	echo "Entered function: multiply"

###############################
# If not one of the known functions print error
else
	echo "Unknown function" 1>&2
	exit 1
fi
